redpanda:
  hosts:
    # change the hostname
    ec2-<IP1...>.compute-1.amazonaws.com:
      # change it to the AMI's user name or delete
      ansible_user: ubuntu
      private_ip: 10.0.21.1
      id: 1
    ec2-<IP2...>.compute-1.amazonaws.com:
      ansible_user: ubuntu
      private_ip: 10.0.21.2
      id: 2
    ec2-<IP3...>.compute-1.amazonaws.com:
      ansible_user: ubuntu
      private_ip: 10.0.21.3
      id: 3
